VISUAL C++ REDISTRIBUTABLE FOR VISUAL STUDIO 2019
Error in installing tensorflow due to the missing of resilient file from 2015.

from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.